import { describe, expect, it } from 'vitest';
import { solveBruteForce, solveWithLogic, Technique, techniqueToDifficulty } from './solver';
import type { Digit } from './types';

/**
 * Fixtures generated by the engine and pinned so these tests are deterministic.
 * Each is a valid, uniquely solvable classic puzzle; `max` is the highest
 * technique level the logic solver needed when the fixture was captured.
 */
const FIXTURES = [
  { name: 'medium via pointing pairs', max: Technique.PointingPair,
    grid: '4..7....66.54..78....83...5.........9..6...177....56.35....2......9..562.19...4..' },
  { name: 'medium via naked/hidden pairs', max: Technique.NakedPair,
    grid: '.37......5....6.2..2.3....1.....9.14...1..23.3.1.2.689.4.8.3..6...79.........24..' },
  { name: 'hard A', max: Technique.NakedTriple,
    grid: '7.3.......8....4..1...5.........6...917..8....5...39.1........5..839....2...4567.' },
  { name: 'hard B', max: Technique.NakedTriple,
    grid: '...8......36.......5..694.....5....3.......29.62.3..1.6.1...5..7..62..8..4....9..' },
  { name: 'expert A', max: Technique.XWing,
    grid: '.8.3....72....4...1.4..5..8.......61.......7.6...729...6.5...9.9.54...1...8..9..4' },
  { name: 'expert B', max: Technique.XWing,
    grid: '.4615.........8.622.87...9...4.15....52..967.....8....7..........1.....4..5...28.' },
  { name: 'expert C', max: Technique.XWing,
    grid: '...1.6.8.........1..5....2..9.4.861.3619.......8.....24..32.........4..7.26....5.' },
] as const;

function decode(encoded: string): (Digit | null)[][] {
  return Array.from({ length: 9 }, (_, row) =>
    Array.from({ length: 9 }, (_, col) => {
      const ch = encoded[row * 9 + col];
      return ch === '.' ? null : (Number(ch) as Digit);
    }));
}

/** The band a technique level belongs to, as the levels just below it. */
const levelBelow: Record<number, number> = {
  [Technique.PointingPair]: Technique.HiddenSingle,
  [Technique.NakedPair]: Technique.PointingPair,
  [Technique.NakedTriple]: Technique.NakedPair,
  [Technique.XWing]: Technique.NakedTriple,
};

describe('logic solver techniques', () => {
  for (const fixture of FIXTURES) {
    describe(fixture.name, () => {
      const puzzle = decode(fixture.grid);

      it('is sound: the logic solution matches brute force exactly', () => {
        const [solution] = solveBruteForce(puzzle);
        const result = solveWithLogic(puzzle);
        expect(result.solved).toBe(true);
        expect(result.grid).toEqual(solution);
        expect(result.maxTechnique).toBe(fixture.max);
        expect(techniqueToDifficulty(result.maxTechnique)).toBe(
          fixture.name.startsWith('medium') ? 'medium' : fixture.name.startsWith('hard') ? 'hard' : 'expert',
        );
      });

      it('is necessary: capping below its band leaves the puzzle unsolved', () => {
        const capped = solveWithLogic(puzzle, levelBelow[fixture.max]);
        expect(capped.solved).toBe(false);
        expect(capped.maxTechnique).toBeLessThanOrEqual(levelBelow[fixture.max]);
        // Partial progress never places a wrong digit.
        const [solution] = solveBruteForce(puzzle);
        capped.grid.forEach((row, r) => row.forEach((digit, c) => {
          if (digit !== null) expect(digit).toBe(solution[r][c]);
        }));
      });
    });
  }

});
