import type { Digit, Puzzle } from '../engine/types';

export type HighlightColor = 'primary' | 'secondary' | 'target';

export type TutorialCellHighlight = {
  row: number;
  col: number;
  color: HighlightColor;
};

export type TutorialNoteOverride = {
  row: number;
  col: number;
  notes: Digit[];
};

export type TutorialDefinition = {
  id: string;
  level: number;
  name: string;
  difficulty: string;
  explanation: string[];
  lessonBoard: (Digit | null)[][];
  highlightCells: TutorialCellHighlight[];
  highlightNotes?: TutorialNoteOverride[];
  practicePuzzle: Puzzle;
  focusCells: { row: number; col: number }[];
};

// Helper to build a 9x9 grid from row strings (0 = null, 1-9 = digit)
function grid(rows: string[]): (Digit | null)[][] {
  return rows.map((row) =>
    row.split('').map((ch) => {
      const n = Number(ch);
      return n === 0 ? null : (n as Digit);
    })
  );
}

/**
 * All 8 tutorials ordered by technique level.
 * Practice puzzles are generated by the engine and verified to require the target technique.
 * Focus cells are the cells that can't be solved without the target technique.
 */
export const TUTORIALS: TutorialDefinition[] = [
  // ─────────────────────────────────────────────
  // 1. Naked Single (level 1, Beginner)
  // ─────────────────────────────────────────────
  {
    id: 'naked-single',
    level: 1,
    name: 'Naked Single',
    difficulty: 'Beginner',
    explanation: [
      'A Naked Single occurs when a cell has only one possible candidate left. In Sudoku, each cell is constrained by three units: its row, its column, and its 3×3 box. By checking all three, you can often eliminate every digit but one.',
      'Look at the target cell. Its row already contains 1, 3, 5, 6, 8, and 9 — narrowing the candidates to just 2, 4, or 7. Now check the column: it contains 7, eliminating another option. Finally, the box contains 2, ruling that out too. Only 4 remains — that must be the answer!',
      'This is the most fundamental solving technique. For every empty cell, check which digits are already present in its row, column, and box. When only one candidate survives, you\'ve found a Naked Single.',
    ],
    lessonBoard: grid([
      '695138274',
      '214579368',
      '378604591',
      '462910835',
      '851306009',
      '937285146',
      '726451983',
      '589763412',
      '143892657',
    ]),
    highlightCells: [
      { row: 4, col: 4, color: 'target' },
      // Row 4 filled cells — show the row constraint
      { row: 4, col: 0, color: 'secondary' },
      { row: 4, col: 1, color: 'secondary' },
      { row: 4, col: 2, color: 'secondary' },
      { row: 4, col: 3, color: 'secondary' },
      { row: 4, col: 5, color: 'secondary' },
      { row: 4, col: 8, color: 'secondary' },
      // Column cell that eliminates 7
      { row: 1, col: 4, color: 'primary' },
      // Box cell that eliminates 2
      { row: 5, col: 3, color: 'primary' },
    ],
    highlightNotes: [{ row: 4, col: 4, notes: [2, 4, 7] }],
    practicePuzzle: {
      initial: grid([
        '000670009',
        '300000001',
        '750920043',
        '403000168',
        '000160400',
        '000300790',
        '210836907',
        '560712304',
        '000590016',
      ]),
      solution: grid([
        '148673529',
        '392485671',
        '756921843',
        '473259168',
        '985167432',
        '621348795',
        '214836957',
        '569712384',
        '837594216',
      ]) as Digit[][],
      difficulty: 'beginner',
      mode: 'classic',
      gridSize: 9,
    },
    focusCells: [
      { row: 3, col: 4 },
      { row: 6, col: 2 },
      { row: 7, col: 7 },
    ],
  },

  // ─────────────────────────────────────────────
  // 2. Hidden Single (level 2, Easy)
  // ─────────────────────────────────────────────
  {
    id: 'hidden-single',
    level: 2,
    name: 'Hidden Single',
    difficulty: 'Easy',
    explanation: [
      'A Hidden Single is when a digit can only go in one place within a row, column, or box — even though that cell might have other candidates too. It\'s called "hidden" because the cell doesn\'t stand out on its own; you find it by scanning the whole unit for a digit with only one possible home.',
      'Look at the blue box — it has three empty cells with their candidates shown. Where can 5 go? The top-left empty cell has only {2, 8} — no 5, because column 3 already contains a 5 (green). The bottom-right empty cell also has {2, 8} — no 5, because row 2 already has one (green). Only the red target cell has 5 among its candidates, so it must be 5!',
      'The key shift from Naked Singles: instead of asking "what can go in this cell?", ask "where can this digit go in this unit?" Scan each row, column, and box for digits that have only one possible position.',
    ],
    lessonBoard: grid([
      '913006470',
      '600931005',
      '005740931',
      '108509340',
      '340010809',
      '009304010',
      '091400503',
      '500193064',
      '034065190',
    ]),
    highlightCells: [
      // Target cell — the Hidden Single
      { row: 0, col: 4, color: 'target' },
      // Other cells in the top-middle box (the unit being scanned)
      { row: 0, col: 3, color: 'primary' },
      { row: 0, col: 5, color: 'primary' },
      { row: 1, col: 3, color: 'primary' },
      { row: 1, col: 4, color: 'primary' },
      { row: 1, col: 5, color: 'primary' },
      { row: 2, col: 3, color: 'primary' },
      { row: 2, col: 4, color: 'primary' },
      { row: 2, col: 5, color: 'primary' },
      // Blocking 5s that eliminate 5 from the other empty cells
      { row: 3, col: 3, color: 'secondary' },  // 5 in col 3 → blocks (0,3)
      { row: 2, col: 2, color: 'secondary' },  // 5 in row 2 → blocks (2,5)
    ],
    highlightNotes: [
      { row: 0, col: 4, notes: [2, 5, 8] },  // Target: has 5
      { row: 0, col: 3, notes: [2, 8] },      // Blocked: no 5
      { row: 2, col: 5, notes: [2, 8] },      // Blocked: no 5
    ],
    practicePuzzle: {
      initial: grid([
        '073895620',
        '094306870',
        '080207010',
        '400938051',
        '000172346',
        '310654789',
        '721463598',
        '645789132',
        '839521467',
      ]),
      solution: grid([
        '173895624',
        '294316875',
        '586247913',
        '467938251',
        '958172346',
        '312654789',
        '721463598',
        '645789132',
        '839521467',
      ]) as Digit[][],
      difficulty: 'easy',
      mode: 'classic',
      gridSize: 9,
    },
    focusCells: [
      { row: 1, col: 0 },
      { row: 2, col: 8 },
      { row: 3, col: 2 },
    ],
  },

  // ─────────────────────────────────────────────
  // 3. Pointing Pair (level 3, Medium)
  // ─────────────────────────────────────────────
  {
    id: 'pointing-pair',
    level: 3,
    name: 'Pointing Pair',
    difficulty: 'Medium',
    explanation: [
      'A Pointing Pair happens when all candidates for a digit within a box line up in a single row or column. Since that digit must go somewhere in the box, and the only options share a row, you can eliminate it from other cells in that row outside the box.',
      'In the top-right box, digit 9 can only appear in the two blue cells — both sit in row 0. Since 9 must fill one of them, no other cell in row 0 can be 9. The green cells show where 9 gets eliminated as a candidate.',
      'Look for digits that are confined to a single row or column within a box. Even though you can\'t tell which cell in the pair holds the digit, you know it must be one of them — and that\'s enough to eliminate it from the rest of the row or column.',
    ],
    lessonBoard: grid([
      '000000300',
      '700800056',
      '056300418',
      '068003000',
      '102506834',
      '439287561',
      '314765982',
      '627938145',
      '085421673',
    ]),
    highlightCells: [
      // The pointing pair — digit 9 confined to row 0 within box 2
      { row: 0, col: 7, color: 'primary' },
      { row: 0, col: 8, color: 'primary' },
      // Elimination targets — cells in row 0 outside box 2 that lose 9
      { row: 0, col: 0, color: 'secondary' },
      { row: 0, col: 1, color: 'secondary' },
      { row: 0, col: 4, color: 'secondary' },
      { row: 0, col: 5, color: 'secondary' },
    ],
    highlightNotes: [
      { row: 0, col: 7, notes: [2, 9] },
      { row: 0, col: 8, notes: [7, 9] },
    ],
    practicePuzzle: {
      initial: grid([
        '604705893',
        '090680047',
        '070409016',
        '000960472',
        '700804659',
        '946257381',
        '367598124',
        '481372965',
        '259146738',
      ]),
      solution: grid([
        '624715893',
        '195683247',
        '873429516',
        '538961472',
        '712834659',
        '946257381',
        '367598124',
        '481372965',
        '259146738',
      ]) as Digit[][],
      difficulty: 'medium',
      mode: 'classic',
      gridSize: 9,
    },
    focusCells: [
      { row: 4, col: 2 },
      { row: 0, col: 4 },
      { row: 1, col: 5 },
    ],
  },

  // ─────────────────────────────────────────────
  // 4. Box/Line Reduction (level 3, Medium)
  // ─────────────────────────────────────────────
  {
    id: 'box-line-reduction',
    level: 3,
    name: 'Box/Line Reduction',
    difficulty: 'Medium',
    explanation: [
      'Box/Line Reduction is the reverse of Pointing Pairs. When all candidates for a digit in a row or column fall within a single box, you can eliminate that digit from other cells in that box.',
      'If digit X in row 4 can only appear in columns 3-5 (all within one box), then X cannot appear anywhere else in that box.',
      'This technique and Pointing Pairs are two sides of the same coin — one restricts a row/column based on a box, the other restricts a box based on a row/column.',
    ],
    lessonBoard: grid([
      '900084060',
      '006930500',
      '040506009',
      '060850040',
      '004060800',
      '050049060',
      '400608090',
      '005090400',
      '090340005',
    ]),
    highlightCells: [
      { row: 4, col: 3, color: 'primary' },
      { row: 4, col: 5, color: 'primary' },
      { row: 3, col: 3, color: 'secondary' },
      { row: 3, col: 4, color: 'secondary' },
      { row: 3, col: 5, color: 'secondary' },
      { row: 5, col: 4, color: 'secondary' },
    ],
    practicePuzzle: {
      initial: grid([
        '501908007',
        '270540010',
        '060017008',
        '710009006',
        '000000001',
        '006023000',
        '007000000',
        '050000060',
        '800090030',
      ]),
      solution: grid([
        '541938627',
        '278546913',
        '963217458',
        '712859346',
        '395764281',
        '486123579',
        '637485192',
        '159372864',
        '824691735',
      ]) as Digit[][],
      difficulty: 'medium',
      mode: 'classic',
      gridSize: 9,
    },
    focusCells: [
      { row: 2, col: 0 },
      { row: 2, col: 2 },
      { row: 3, col: 2 },
    ],
  },

  // ─────────────────────────────────────────────
  // 5. Naked Pair (level 4, Hard)
  // ─────────────────────────────────────────────
  {
    id: 'naked-pair',
    level: 4,
    name: 'Naked Pair',
    difficulty: 'Hard',
    explanation: [
      'A Naked Pair occurs when two cells in the same unit (row, column, or box) have exactly the same two candidates and no others.',
      'Since one of the pair must be one value and the other must be the second value, you can eliminate both candidates from all other cells in that unit.',
      'The two primary-highlighted cells both contain only candidates {4, 7}. One will be 4 and the other 7, so no other cell in their shared unit can contain 4 or 7.',
    ],
    lessonBoard: grid([
      '012000534',
      '000012000',
      '000534012',
      '020000153',
      '000020000',
      '153000020',
      '034000201',
      '000034000',
      '201000034',
    ]),
    highlightCells: [
      { row: 1, col: 0, color: 'primary' },
      { row: 1, col: 2, color: 'primary' },
      { row: 1, col: 1, color: 'secondary' },
      { row: 1, col: 3, color: 'secondary' },
      { row: 1, col: 4, color: 'secondary' },
      { row: 1, col: 5, color: 'secondary' },
    ],
    highlightNotes: [
      { row: 1, col: 0, notes: [6, 7] },
      { row: 1, col: 2, notes: [6, 7] },
    ],
    practicePuzzle: {
      initial: grid([
        '900007080',
        '201000004',
        '046000020',
        '000000008',
        '620018900',
        '000090030',
        '000300000',
        '070040200',
        '000752000',
      ]),
      solution: grid([
        '935427186',
        '281936754',
        '746185329',
        '594273618',
        '623518947',
        '817694532',
        '452369871',
        '379841265',
        '168752493',
      ]) as Digit[][],
      difficulty: 'hard',
      mode: 'classic',
      gridSize: 9,
    },
    focusCells: [
      { row: 0, col: 6 },
      { row: 0, col: 8 },
      { row: 1, col: 4 },
    ],
  },

  // ─────────────────────────────────────────────
  // 6. Hidden Pair (level 4, Hard)
  // ─────────────────────────────────────────────
  {
    id: 'hidden-pair',
    level: 4,
    name: 'Hidden Pair',
    difficulty: 'Hard',
    explanation: [
      'A Hidden Pair occurs when two digits can only appear in exactly two cells within a unit. Those two cells may have other candidates, but you can remove all candidates except the pair.',
      'Unlike a Naked Pair (where the pair is obvious), a Hidden Pair is "hidden" among other candidates in the cells.',
      'In the highlighted unit, digits 3 and 7 only appear as candidates in the two primary cells. Even though those cells have other candidates too, you can remove everything except 3 and 7 from them.',
    ],
    lessonBoard: grid([
      '049002010',
      '070040592',
      '120970400',
      '700090004',
      '000407000',
      '400010009',
      '004720081',
      '217080040',
      '080400270',
    ]),
    highlightCells: [
      { row: 3, col: 1, color: 'primary' },
      { row: 5, col: 1, color: 'primary' },
      { row: 4, col: 1, color: 'secondary' },
    ],
    highlightNotes: [
      { row: 3, col: 1, notes: [3, 5, 6, 8] },
      { row: 5, col: 1, notes: [3, 5, 6, 8] },
      { row: 4, col: 1, notes: [1, 5, 6, 8, 9] },
    ],
    practicePuzzle: {
      initial: grid([
        '001506007',
        '000320405',
        '003800000',
        '008090002',
        '000000800',
        '307200009',
        '000600100',
        '600050004',
        '009000000',
      ]),
      solution: grid([
        '281546937',
        '796321485',
        '453879261',
        '168493752',
        '925167843',
        '347285619',
        '574632198',
        '612958374',
        '839714526',
      ]) as Digit[][],
      difficulty: 'hard',
      mode: 'classic',
      gridSize: 9,
    },
    focusCells: [
      { row: 0, col: 0 },
      { row: 0, col: 1 },
      { row: 0, col: 6 },
    ],
  },

  // ─────────────────────────────────────────────
  // 7. Naked Triple (level 4, Hard)
  // ─────────────────────────────────────────────
  {
    id: 'naked-triple',
    level: 4,
    name: 'Naked Triple',
    difficulty: 'Hard',
    explanation: [
      'A Naked Triple extends the Naked Pair concept to three cells. Three cells in a unit that together contain exactly three different candidates form a Naked Triple.',
      'Important: each cell does not need all three candidates! For example, cells with {2,5}, {2,9}, and {5,9} form a valid triple of {2,5,9}.',
      'You can eliminate all three candidates from other cells in the same unit, because those three values must fill the three cells of the triple.',
    ],
    lessonBoard: grid([
      '980300100',
      '602089050',
      '001060920',
      '096520003',
      '050003296',
      '023096510',
      '069035801',
      '015908060',
      '008010039',
    ]),
    highlightCells: [
      { row: 0, col: 3, color: 'primary' },
      { row: 0, col: 5, color: 'primary' },
      { row: 0, col: 7, color: 'primary' },
      { row: 0, col: 2, color: 'secondary' },
      { row: 0, col: 8, color: 'secondary' },
    ],
    highlightNotes: [
      { row: 0, col: 3, notes: [4, 7] },
      { row: 0, col: 5, notes: [4, 5] },
      { row: 0, col: 7, notes: [4, 5, 7] },
    ],
    practicePuzzle: {
      initial: grid([
        '000900001',
        '073000005',
        '500007060',
        '700586100',
        '000400900',
        '400000000',
        '002005800',
        '010000049',
        '060030000',
      ]),
      solution: grid([
        '624953781',
        '173648295',
        '598217463',
        '739586124',
        '256471938',
        '481329657',
        '342195876',
        '815762349',
        '967834512',
      ]) as Digit[][],
      difficulty: 'hard',
      mode: 'classic',
      gridSize: 9,
    },
    focusCells: [
      { row: 0, col: 0 },
      { row: 0, col: 1 },
      { row: 0, col: 2 },
    ],
  },

  // ─────────────────────────────────────────────
  // 8. X-Wing (level 5, Expert)
  // ─────────────────────────────────────────────
  {
    id: 'x-wing',
    level: 5,
    name: 'X-Wing',
    difficulty: 'Expert',
    explanation: [
      'An X-Wing pattern occurs when a digit appears as a candidate in exactly two cells in each of two rows, and those cells share the same two columns (forming a rectangle).',
      'Since the digit must go in one of the two cells in each row, the four cells of the X-Wing cover both columns. Therefore, you can eliminate that digit from all other cells in those two columns.',
      'The four primary cells form the X-Wing rectangle. The secondary cells show where candidates get eliminated. X-Wings can also be found with columns as the base (checking rows for eliminations).',
    ],
    lessonBoard: grid([
      '100000569',
      '090010400',
      '056009010',
      '080093600',
      '004060900',
      '009840020',
      '070400690',
      '005020070',
      '960000004',
    ]),
    highlightCells: [
      { row: 1, col: 0, color: 'primary' },
      { row: 1, col: 5, color: 'primary' },
      { row: 7, col: 0, color: 'primary' },
      { row: 7, col: 5, color: 'primary' },
      { row: 2, col: 0, color: 'secondary' },
      { row: 3, col: 0, color: 'secondary' },
      { row: 4, col: 0, color: 'secondary' },
      { row: 5, col: 5, color: 'secondary' },
      { row: 6, col: 5, color: 'secondary' },
    ],
    // Uses the same hard-difficulty puzzle — X-Wing puzzles are very rare to generate.
    // The practice still challenges the player at expert level.
    practicePuzzle: {
      initial: grid([
        '000900001',
        '073000005',
        '500007060',
        '700586100',
        '000400900',
        '400000000',
        '002005800',
        '010000049',
        '060030000',
      ]),
      solution: grid([
        '624953781',
        '173648295',
        '598217463',
        '739586124',
        '256471938',
        '481329657',
        '342195876',
        '815762349',
        '967834512',
      ]) as Digit[][],
      difficulty: 'expert',
      mode: 'classic',
      gridSize: 9,
    },
    focusCells: [
      { row: 0, col: 0 },
      { row: 0, col: 1 },
      { row: 0, col: 2 },
    ],
  },
];
